/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SCard;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manh Cuong
 */
public class TrangChu extends javax.swing.JFrame {
     static infoTV info;
    static theTV thetv;
    private Boolean input= false;
    private boolean cardready= false;
    private boolean connected= false;
    public byte[] rsaPubKey = new byte[128];
    /**
     * Creates new form trangChu
     */
    public TrangChu() {
        info = new infoTV();
        thetv = new theTV();
        initComponents();
    }
    
    public void setCommandAPDU(byte[] cmnds, byte lc,byte[] data, byte le) {
        txt_cla.setText(thetv.byteToHex(cmnds[0]));
        txt_ins.setText(thetv.byteToHex(cmnds[1]));
        txt_p1.setText(thetv.byteToHex(cmnds[2]));
        txt_p2.setText(thetv.byteToHex(cmnds[3]));
        txt_le.setText(thetv.byteToHex(lc));
        //data
        String temp = "";
        for (int i = 0; i < data.length; i++) {
            temp += thetv.byteToHex(data[i]);
            temp += " ";
        }
        txt_lc.setText(temp);
        txt_cmd.setText(thetv.byteToHex(le));
    }
    //hien thi apdu phan hoi len
    public void setResponseAPDU(byte[] datares,short le) {
        int status1 = thetv.resAPDU.getSW1();
        int status2 = thetv.resAPDU.getSW2();
        txt_sw1.setText(thetv.shorttoHex((short)status1));
        txt_sw2.setText(thetv.shorttoHex((short)status2));
        if (le != 0 && datares.length != 0) {
            //hien thi du lieu ra
            String temp = "";
            for (int i = 0; i < datares.length; i++) {
                temp += thetv.byteToHex(datares[i]);
                temp += " ";
            }
            txt_respon.setText(temp);
        }
    }   
    FormGame viewFormGame = new FormGame();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cla = new javax.swing.JTextField();
        txt_ins = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_p1 = new javax.swing.JTextField();
        txt_p2 = new javax.swing.JTextField();
        txt_le = new javax.swing.JTextField();
        txt_lc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_cmd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_sw1 = new javax.swing.JTextField();
        txt_sw2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_respon = new javax.swing.JTextField();
        btn_init = new javax.swing.JButton();
        btn_sendata = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        Button_Unblock = new javax.swing.JButton();
        Button_connect = new javax.swing.JButton();
        Button_Disconnect = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        anhthe = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_idtv = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_ngaysinh = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_quequan = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_gioitinh = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_sodu = new javax.swing.JLabel();
        Btn_thayanh = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Btn_Xemtt = new javax.swing.JButton();
        bnt_naptien = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        btn_changePIN = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        txt_TTKT = new javax.swing.JLabel();
        txt_TTN = new javax.swing.JLabel();
        txt_pin = new javax.swing.JPasswordField();

        jTextField11.setText("jTextField11");

        jButton7.setText("jButton7");

        jTextField12.setText("jTextField12");

        jTextField13.setText("jTextField13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Trang chủ ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("CLA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("INS");

        txt_cla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("P1");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("P2");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("LC");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("LE");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Dữ Liệu");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("APDU Phản Hồi");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("SW1");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("SW2");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Dữ Liệu");

        btn_init.setBackground(new java.awt.Color(204, 255, 204));
        btn_init.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_init.setForeground(new java.awt.Color(0, 204, 0));
        btn_init.setText("Khởi tạo");
        btn_init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_initActionPerformed(evt);
            }
        });

        btn_sendata.setBackground(new java.awt.Color(204, 255, 204));
        btn_sendata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sendata.setForeground(new java.awt.Color(0, 204, 0));
        btn_sendata.setText("Gửi dữ liệu đến Applet");
        btn_sendata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendataActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(255, 204, 204));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 0, 0));
        btn_clear.setText("Xóa thẻ");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        Button_Unblock.setBackground(new java.awt.Color(204, 255, 204));
        Button_Unblock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_Unblock.setForeground(new java.awt.Color(0, 204, 0));
        Button_Unblock.setText("Mở khóa thẻ");
        Button_Unblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UnblockActionPerformed(evt);
            }
        });

        Button_connect.setBackground(new java.awt.Color(204, 255, 204));
        Button_connect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_connect.setForeground(new java.awt.Color(0, 204, 0));
        Button_connect.setText("Kết nối ");
        Button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_connectActionPerformed(evt);
            }
        });

        Button_Disconnect.setBackground(new java.awt.Color(255, 204, 204));
        Button_Disconnect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_Disconnect.setForeground(new java.awt.Color(255, 0, 0));
        Button_Disconnect.setText("Ngắt kết nối");
        Button_Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DisconnectActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Thông tin thẻ chơi ");

        anhthe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setText("ID thẻ :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setText("Họ và tên : ");

        txt_idtv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_idtv.setForeground(new java.awt.Color(102, 102, 255));

        txt_hoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_hoten.setForeground(new java.awt.Color(102, 102, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jLabel22.setText("Ngày sinh : ");

        txt_ngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ngaysinh.setForeground(new java.awt.Color(102, 102, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 255));
        jLabel24.setText("Quê quán  :");

        txt_quequan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_quequan.setForeground(new java.awt.Color(102, 102, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 255));
        jLabel26.setText("Giới tính :");

        txt_gioitinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_gioitinh.setForeground(new java.awt.Color(102, 102, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 255));
        jLabel28.setText("Số tiền khả dụng :");

        txt_sodu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sodu.setForeground(new java.awt.Color(102, 102, 255));

        Btn_thayanh.setBackground(new java.awt.Color(204, 255, 204));
        Btn_thayanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn_thayanh.setForeground(new java.awt.Color(0, 204, 0));
        Btn_thayanh.setText("Thay ảnh");
        Btn_thayanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_thayanhActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 255));
        jLabel30.setText("(VNÐ)");

        jLabel31.setBackground(new java.awt.Color(102, 102, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 255));
        jLabel31.setText("Nhập mã pin :");

        Btn_Xemtt.setBackground(new java.awt.Color(204, 255, 204));
        Btn_Xemtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn_Xemtt.setForeground(new java.awt.Color(0, 204, 0));
        Btn_Xemtt.setText("Xác nhận");
        Btn_Xemtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XemttActionPerformed(evt);
            }
        });

        bnt_naptien.setBackground(new java.awt.Color(204, 255, 204));
        bnt_naptien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bnt_naptien.setForeground(new java.awt.Color(0, 204, 0));
        bnt_naptien.setText("Nạp tiền");
        bnt_naptien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_naptienActionPerformed(evt);
            }
        });

        btn_play.setBackground(new java.awt.Color(204, 255, 204));
        btn_play.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_play.setForeground(new java.awt.Color(0, 204, 0));
        btn_play.setText("Chơi game");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });

        btn_changePIN.setBackground(new java.awt.Color(204, 255, 204));
        btn_changePIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_changePIN.setForeground(new java.awt.Color(0, 204, 0));
        btn_changePIN.setText("Thay đổi mã pin");
        btn_changePIN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_changePINMouseMoved(evt);
            }
        });
        btn_changePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePINActionPerformed(evt);
            }
        });

        btn_capnhat.setBackground(new java.awt.Color(204, 255, 204));
        btn_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_capnhat.setForeground(new java.awt.Color(0, 204, 0));
        btn_capnhat.setText("Thay đổi thông tin");
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        txt_TTKT.setText("unknow");

        txt_TTN.setText("unknow");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_cla, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt_respon, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(anhthe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Btn_thayanh)
                                            .addComponent(btn_play)
                                            .addComponent(bnt_naptien)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(txt_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(txt_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_le, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_lc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel19))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_idtv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                                    .addComponent(txt_hoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_sodu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_sendata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_init, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Button_Unblock, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_Disconnect, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(Button_connect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_TTN, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(txt_TTKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(243, 243, 243))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(txt_sw1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txt_sw2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_changePIN)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn_Xemtt)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_le, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cmd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_sw1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sw2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_respon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_init, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Disconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TTN))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Unblock, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sendata, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TTKT))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Xemtt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(anhthe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_thayanh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bnt_naptien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_play, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_changePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(txt_idtv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_sodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(1, 1, 1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(194, 194, 194))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_claActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claActionPerformed

    private void btn_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initActionPerformed
        // TODO add your handling code here:
         if(connected == true){
            if (input == false) {
                FormNhapThongTinNguoiChoi viewFormnhapthongtinnguoichoi = new FormNhapThongTinNguoiChoi();
                viewFormnhapthongtinnguoichoi.setVisible(true);
                viewFormnhapthongtinnguoichoi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
            else JOptionPane.showMessageDialog(null, "Thẻ đã có dữ liệu");
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_btn_initActionPerformed

    private void btn_sendataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendataActionPerformed
        // TODO add your handling code here:
         if(connected == true){
        if (input == false) {
            setImage(info.getAvatar());
            getImage(info.getAvatar());
            //chuyen du lieu xuong applet
            String hoten = info.getHoten();
            String ngaysinh = info.getNgaysinh();
            String quequan = info.getQuequan();
            String pin = info.getMapin();
            String idtv= info.getIdtv();
            String gioitinh = info.getGioitinh();
            String tientk=info.getTientk();
            
            String arraysend = hoten.concat(".")
                    .concat(ngaysinh).concat(".")
                    .concat(quequan).concat(".")
                    .concat(gioitinh).concat(".")
                    .concat(idtv).concat(".")
                    .concat(tientk)
                    .concat(".")
                    .concat(pin);
            
            System.out.println("send:"+arraysend);
            int lc = arraysend.length();
            byte datalen = (byte) lc; //do dai du lieu gui vao applet
            byte[] cmd = {(byte) 0xA0, (byte) 0x00, (byte) 0x00, (byte) 0x00};
            byte[] data = arraysend.getBytes();
            setCommandAPDU(cmd, (byte)lc, data, (byte)0);
            thetv.sendAPDUtoApplet(cmd, data);
            byte[] dataRes = thetv.resAPDU.getData();
            int le = thetv.resAPDU.getNr();
            setResponseAPDU(dataRes, (byte)le);
            String tach = new String(dataRes) ;
            System.out.print("a:"+tach);
            String[] a = tach.split(":");
            String ht = a[0];
            String ns = a[1];
            String qq = a[2];
            String gt = a[3];
            String msv = a[4];
            String stttk = a[5];
            txt_idtv.setText(msv);
            txt_hoten.setText(ht);
            txt_ngaysinh.setText(ns);
            txt_quequan.setText(qq);
            txt_gioitinh.setText(gt);
            txt_sodu.setText(stttk);
            byte[] cmd1 = {(byte) 0xA0, (byte) 0x21, (byte) 0x00, (byte) 0x00};
            thetv.sendAPDUtoApplet(cmd1);
            byte[] b = thetv.resAPDU.getData();
            String sodu = "";
            for (int i = 0; i < b.length; i++) {
                sodu += thetv.byteToHex(b[i]);
            }
            txt_sodu.setText(""+Integer.valueOf(sodu,16).intValue());
            input = true;
        } else {
            JOptionPane.showMessageDialog(null, "Thẻ đã có dữ liệu.");
        }
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_btn_sendataActionPerformed

    private void Button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_connectActionPerformed
        // TODO add your handling code here:
        if(thetv.connectApplet() == true){//thiet lap ket noi
        byte[] cmd = {(byte) 0x00, (byte) 0xA4, (byte) 0x04, (byte) 0x00};// select
        //mang data gui di la RID,PIX
        byte[] data = {(byte) 0x11, (byte) 0x22, (byte) 0x33, (byte) 0x44, (byte) 0x55, (byte) 0x00};
        byte lc = 6;
        byte le_expect = 2;
        setCommandAPDU(cmd, lc, data, le_expect);//hien thi apdu cmd
        thetv.sendAPDUtoApplet(cmd, data);
        byte[] dataRes = thetv.resAPDU.getData();
        int le = thetv.resAPDU.getNr();
        setResponseAPDU(dataRes, (short)le);//hien thi du lieu phan hoi tu applet
        JOptionPane.showMessageDialog(this, "Kết nối  thành công.");
        txt_TTKT.setText("Succes");
        txt_TTN.setText("");
        Button_connect.setText("Connecting");
       
        connected = true;
        }else JOptionPane.showMessageDialog(this, "Kết nối không thành công. Hãy thử lại.");
    }//GEN-LAST:event_Button_connectActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
         if(connected ==true){
            if(input == false){ JOptionPane.showMessageDialog(null, "Thẻ chưa có dữ liệu.");
            }else{
                byte[] cmd = {(byte) 0xA0, (byte) 0x18, (byte) 0x00, (byte) 0x00};
                byte[] data = {0};
                setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
                thetv.sendAPDUtoApplet(cmd);
                byte[] dataRes= thetv.resAPDU.getData();
                int le= thetv.resAPDU.getNr();
                setResponseAPDU(dataRes,(short) le);
                txt_quequan.setText("");
                txt_idtv.setText("");
                txt_hoten.setText("");
                txt_ngaysinh.setText("");
                txt_pin.setText("");
                txt_gioitinh.setText("");
                txt_sodu.setText("");
                JOptionPane.showMessageDialog(null, "Thẻ đã xóa dữ liệu.");
                input=false;
            }   
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void Btn_thayanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_thayanhActionPerformed
        // TODO add your handling code here:
         if(connected == true && cardready == true){
        JFileChooser fc = new JFileChooser();
        int returnValue = fc.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            BufferedImage bimage;
            try{
                bimage = ImageIO.read(file);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bimage, "jpg", baos);
                byte[] img = baos.toByteArray();
                setImage(img);
                getImage(img);
                info.setAvatar(img);
                JOptionPane.showMessageDialog(this, "Thay ảnh thành công.");
            }catch(IOException e){
                e.printStackTrace();
            }
        }
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ.");
    }//GEN-LAST:event_Btn_thayanhActionPerformed

    private void btn_changePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changePINActionPerformed
        // TODO add your handling code here:
          if(connected == true && cardready == true){
                FormEditMaPin updatepin= new FormEditMaPin();
                updatepin.setVisible(true);
                updatepin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");                                             
    }//GEN-LAST:event_btn_changePINActionPerformed

    private void bnt_naptienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_naptienActionPerformed
        // TODO add your handling code here:
          if(connected ==true && cardready == true){
                FormNap naptien = new FormNap();
                naptien.setVisible(true);
                naptien.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_bnt_naptienActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        viewFormGame.setVisible(true);
        viewFormGame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here
        if(connected == true && cardready == true){
                EditThongTin viewEditThongTin = new EditThongTin(txt_hoten.getText(),txt_ngaysinh.getText(),txt_quequan.getText(), txt_gioitinh.getText());
                viewEditThongTin.setVisible(true);
                viewEditThongTin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
        
        
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void btn_changePINMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changePINMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_changePINMouseMoved

    private void Button_DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DisconnectActionPerformed
        // TODO add your handling code here:
        if(thetv.disconnectApplet() == true){
        txt_quequan.setText("");
        txt_idtv.setText("");
        txt_hoten.setText("");
        txt_ngaysinh.setText("");
        txt_pin.setText("");
        txt_gioitinh.setText("");
        txt_sodu.setText("");
        anhthe.setIcon(null);
        Button_connect.setText("Kết nối");
        Button_Disconnect.setText("Đã ngắt kết nối");
        txt_respon.setText("");
        txt_sw1.setText("");
        txt_sw2.setText("");
        txt_cmd.setText("");
        txt_cla.setText("");
        txt_ins.setText("");
        txt_p1.setText("");
        txt_p2.setText("");
        txt_le.setText("");
        txt_lc.setText("");
        connected = false;
        cardready = false;
        txt_TTN.setText("Succes");
        txt_TTKT.setText("");
        }
        else JOptionPane.showMessageDialog(this, "Ngắt kết nối không thành công.");
    }//GEN-LAST:event_Button_DisconnectActionPerformed

    private void Button_UnblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UnblockActionPerformed
        // TODO add your handling code here:
         if(connected==true){
            byte[] cmd = {(byte) 0xA0, (byte) 0x04, (byte) 0x00, (byte) 0x00};
            byte[] data= {0};
            setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
            thetv.sendAPDUtoApplet(cmd);
            byte[] dataRes= thetv.resAPDU.getData();
            int le= thetv.resAPDU.getNr();
            setResponseAPDU(dataRes,(short) le);//hien thi du lieu phan hoi tu applet
            JOptionPane.showMessageDialog(null, "Thẻ đã được mở khóa.");
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_Button_UnblockActionPerformed

    private void Btn_XemttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XemttActionPerformed
        // TODO add your handling code here:
        if(connected == true){
            String pin = Arrays.toString(txt_pin.getPassword());
            if(check_pin(pin) == 0) JOptionPane.showMessageDialog(null,"Mã PIN sai. Vui lòng nhập lại.");
            else if (check_pin(pin) == 1){
                cardready =true;
                getImage(info.getAvatar());
                byte[] cmd = {(byte) 0xA0, (byte) 0x01, (byte) 0x00, (byte) 0x00};
                byte[] data= {0};
                setCommandAPDU(cmd,(byte)0, data, (byte)0);//hien thi apdu cmd len GUI
                thetv.sendAPDUtoApplet(cmd);
                byte[] dataRes = thetv.resAPDU.getData();
                int le = thetv.resAPDU.getNr();
                setResponseAPDU(dataRes, (byte)le);//hien thi du lieu phan hoi tu applet
                String tach = new String(dataRes) ;
                //System.out.print("a:"+tach);
                 String[] a = tach.split(":");
                 String ht = a[0];
                 String ns = a[1];
                 String qq = a[2];
                 String gt = a[3];
                 String msv = a[4];
                 String stttk = a[5];
                 txt_idtv.setText(msv);
                 txt_hoten.setText(ht);
                 txt_ngaysinh.setText(ns);
                 txt_quequan.setText(qq);
                 txt_gioitinh.setText(gt);
                txt_sodu.setText(stttk);
                byte[] cmd1 = {(byte) 0xA0, (byte) 0x21, (byte) 0x00, (byte) 0x00};
                thetv.sendAPDUtoApplet(cmd1);
                byte[] b = thetv.resAPDU.getData();
                String soTTTK = "";
                for (int i = 0; i < b.length; i++) {
                    soTTTK += thetv.byteToHex(b[i]);
                }
                int tien = Integer.valueOf(soTTTK,16).intValue();
                txt_sodu.setText(""+tien);
            }else JOptionPane.showMessageDialog(null, "Bạn đã nhập sai quá số lần cho phép. Thẻ đã bị khóa!");
        }else JOptionPane.showMessageDialog(null, "Chưa connect thẻ");
    }//GEN-LAST:event_Btn_XemttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }
    
     private void setImage(byte [] img){
        if(img == null) return;
        byte[] cmd = {(byte) 0xA0, (byte) 0x06, (byte) 0x01, (byte) 0x00};
        thetv.sendAPDUtoApplet(cmd);
        int sendlen = img.length;
        System.out.println("ảnh gửi:" +img);
        byte[] cmnd = {(byte) 0xA0, (byte) 0x06, (byte) 0x02, (byte) 0x00};
        int pointer = 0;
        byte[] temp = new byte[255];
        int datalen = 255;
        while(sendlen >0){
            System.arraycopy(img, pointer, temp, 0, datalen);
            thetv.sendAPDUtoApplet(cmnd, temp);
            pointer += 255;
            sendlen -=255;
            if(sendlen <255){
                datalen = sendlen;
            }
        }
    }
    private void getImage(byte [] img){
        if(img == null) return;
        try {
        byte[] cmd = {(byte) 0xA0, (byte) 0x07, (byte) 0x01, (byte) 0x00};
        thetv.sendAPDUtoApplet(cmd);
        int sendlen = img.length;
        byte[] cmnd = {(byte) 0xA0, (byte) 0x07, (byte) 0x02, (byte) 0x00};
        byte[] resimg= new byte[sendlen];
        int pointer=0;
        int datalen = 255;
        while(sendlen >0){
            thetv.sendAPDUtoApplet(cmnd);
            byte[] temp = thetv.resAPDU.getData();
            System.arraycopy(temp, 0, resimg, pointer, datalen);
            pointer += 255;
            sendlen -= 255;
            if(sendlen < 255){
                datalen = sendlen;
            }
        }
        System.out.println("ảnh res:" +resimg);
        ByteArrayInputStream bais= new ByteArrayInputStream(resimg);
        BufferedImage b;
        b = ImageIO.read(bais);
        ImageIcon icon= new ImageIcon(b.getScaledInstance(anhthe.getWidth(),anhthe.getHeight(), Image.SCALE_SMOOTH));
        icon.getImage();
        anhthe.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int check_pin(String pin) {
        short lc = (short) pin.length(); //do dai du lieu gui vao applet
        short le = 1;//du lieu nhan mong doi (Le)
        byte[] cmd = {(byte) 0xA0, (byte) 0x02, (byte) 0x00, (byte) 0x00};
        byte[] data = pin.getBytes();
        setCommandAPDU(cmd, (byte)lc, data,(byte)le);
        thetv.sendAPDUtoApplet(cmd, data);
        byte[] dataRes = thetv.resAPDU.getData();
        int lenRes= thetv.resAPDU.getNr() ;
        setResponseAPDU(dataRes, (byte)lenRes);
       
        if (dataRes[0] == (byte)0x01) {
            return 1;
        } else if(dataRes[0] == (byte)0x00){
            return 0;
        }else return 2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Xemtt;
    private javax.swing.JButton Btn_thayanh;
    private javax.swing.JButton Button_Disconnect;
    private javax.swing.JButton Button_Unblock;
    private javax.swing.JButton Button_connect;
    private javax.swing.JLabel anhthe;
    private javax.swing.JButton bnt_naptien;
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_changePIN;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_init;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_sendata;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JLabel txt_TTKT;
    private javax.swing.JLabel txt_TTN;
    private javax.swing.JTextField txt_cla;
    private javax.swing.JTextField txt_cmd;
    private javax.swing.JLabel txt_gioitinh;
    private javax.swing.JLabel txt_hoten;
    private javax.swing.JLabel txt_idtv;
    private javax.swing.JTextField txt_ins;
    private javax.swing.JTextField txt_lc;
    private javax.swing.JTextField txt_le;
    private javax.swing.JLabel txt_ngaysinh;
    private javax.swing.JTextField txt_p1;
    private javax.swing.JTextField txt_p2;
    private javax.swing.JPasswordField txt_pin;
    private javax.swing.JLabel txt_quequan;
    private javax.swing.JTextField txt_respon;
    private javax.swing.JLabel txt_sodu;
    private javax.swing.JTextField txt_sw1;
    private javax.swing.JTextField txt_sw2;
    // End of variables declaration//GEN-END:variables
}
